### ISSUE TITLE
Check the JWT token against the trusted issuers

### ISSUE THREAD

**Issue by viklund** [neicnordic/sda-s3proxy#355]
The s3proxy should check the auth-token against a list of trusted issuers, as specified in the JWK and also some configuration or something.

A/C:
 - Test that this actually works the way we think (check jocke's comment)

**Comment by jbygdell** [comment]
If `server.jwtpubkeyurl` is set to the `JWK` endpoint of the OIDC server a token supplied by that OIDC instance is trusted.

`server.jwtpubkeyurl` and server`jwtpubkeypath` can be used at the same time, thus making it possible to allow both external OIDC servers like `LS-AAI` to work side-by-side with our auth service.

**Comment by jbygdell** [comment]
Since we explicitly only parses the first public key a server provides, we need to make some changes for this to work properly: (https://github.com/neicnordic/sda-s3proxy/blob/a3f4d9b3ec9c906692bb604c5317b7dccfa9c978/userauth.go#L171)



Closing this in favor of neicnordic/sensitive-data-archive#201
